spring.application.name: core-api
spring.profiles.active: local

spring:
  config:
    import:
      - auth.yml
#      - clients-aws.yml
      - clients-oauth.yml
      - classpath:kafka/kafka-producer.yml
      - notification.yml
      - storage-core.yml
      - logging.yml
  web.resources.add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

image:
  post-dir: complete-mission-post
  character-dir: default-character

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 8083

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live
