version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/namu-server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: deploy.sh
      timeout: 90
      runas: ubuntu
  ValidateService:
    - location: healthCheck.sh
      timeout: 90
      runas: ubuntu
