plugins {
    id 'java-library'
    id 'org.springframework.boot' apply(false)
    id 'io.spring.dependency-management'
}

apply from: 'lint.gradle'

allprojects {
    group = "${projectGroup}"
    version = "${applicationVersion}"
    sourceCompatibility = project.javaVersion

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'
//    apply plugin: 'org.asciidoctor.jvm.convert'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudDependenciesVersion}"
        }
    }

    dependencies {
        compileOnly 'org.jetbrains:annotations:23.0.0'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
    }

    configurations {
        configureEach {
            exclude group:'org.springframework.boot', module: 'spring-boot-starter-logging'
            exclude group: 'commons-logging', module: 'commons-logging'
        }
    }

//    ext {
//        set('springCloudVersion', "2023.0.0")
//        snippetsDir = file('build/generated-snippets')
//    }

//    asciidoctor {
//        inputs.dir snippetsDir
//        configurations 'asciidoctorExt'
//        dependsOn test
//    }
//
//    bootJar {
//        dependsOn asciidoctor
//        from("${asciidoctor.outputDir}/html5") {
//            into 'static/docs'
//        }
//    }

    bootJar.enabled = false
    jar.enabled = true

    test {
        useJUnitPlatform {
            excludeTags('dev')
        }
    }

    tasks.named('test') {
        useJUnitPlatform()
//        outputs.dir snippetsDir
    }

//    tasks.register('copyDocument', Copy) {
//        dependsOn asciidoctor
//        from file("build/docs/asciidoc/")
//        into file("src/main/resources/static/docs")
//    }
}
