### Application version ###
applicationVersion=0.0.1-SNAPSHOT

### Project configs ###
projectGroup=univ.earthbreaker.namu
javaVersion=17

### Spring dependency versions ###
springBootVersion=3.2.2
springDependencyManagementVersion=1.1.4
springCloudDependenciesVersion=2023.0.0

## Documentation version ##
asciidoctorJvmConvert=3.3.2
