pluginManagement {
    plugins {
        id 'java'
        id 'org.springframework.boot' version "${springBootVersion}"
        id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
        id 'org.asciidoctor.jvm.convert' version "${asciidoctorJvmConvert}"
    }
}

rootProject.name = 'namu'

include 'app:api', 'app:batch'

include 'core:domain', 'core:storage'

include 'services:auth', 'services:notification'

include 'clients:oauth', 'clients:aws', 'clients:image', 'clients:sse'

include 'event'

include 'support:logging'

include 'server:external', 'server:internal'

include 'tests:api-docs'
