pluginManagement {
    plugins {
        id 'java'
        id 'org.springframework.boot' version "${springBootVersion}"
        id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
        id 'org.asciidoctor.jvm.convert' version "${asciidoctorJvmConvert}"
    }
}

rootProject.name = 'namu'

include 'app:api', 'app:batch', 'app:kafka-consumer'

include 'core:domain', 'core:storage'

include 'infra:storage', 'infra:client', 'infra:kafka', 'infra:notification', 'infra:oauth'

include 'event'

include 'support:logging'

include 'server:external'

include 'tests:api-docs'
