bootJar.enabled = true
jar.enabled = false

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation project(":core:domain")
    implementation project(":core:service")
    implementation project(":support:logging")

    runtimeOnly project(":infra:storage")
    runtimeOnly project(":infra:client")
    runtimeOnly project(":infra:kafka")
    runtimeOnly project(":infra:notification")

    testImplementation project(":tests:api-docs")
}

tasks.register('copyResourcesConfig', Copy) {
    from project(':core:service').file('src/main/resources')
    from project(':infra:storage').file('src/main/resources')
    from project(':infra:client').file('src/main/resources')
    from project(':infra:kafka').file('src/main/resources')
    from project(':infra:notification').file('src/main/resources')
    from project(':support:logging').file('src/main/resources')

    into file("$projectDir/build/resources/main")

    include '*.yml'
    include '/firebase/*.json'
}

processResources.dependsOn('copyResourcesConfig')
