spring.profiles.active: local

spring:
  config:
    import:
      - classpath:logging/logging.yml
  web.resources.add-mappings: false

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
