### 미션 조회
GET /v1/missions
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 미션 인증 성공
POST /v1/missions/certification/1 HTTP/1.1
Host: localhost:8080
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{access_token}}

--boundary
Content-Disposition: form-data; name="imageFile"; filename="인증성공사진.png"
Content-Type: image/png

< ./인증성공사진.png

--boundary
Content-Disposition: form-data; name="content"

인증 성공한 사진과 함께 작성된 글
--boundary

### 미션 인증 실패
PATCH /v1/missions/certification/2
Host: localhost:8080
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{access_token}}
