spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

---
spring.config.activate.on-profile: local-dev

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true

database:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${db.database.core.url}
      username: ${db.database.core.username}
      password: ${db.database.core.password}

---
spring.config.activate.on-profile: prod
