dependencies {
    implementation project(":core:core-domain")
    implementation project(":core:core-auth")

    implementation project(":batch:batch-core")

    implementation project(":external:oauth")
    implementation project(":external:aws")
    implementation project(":external:notification")

    implementation project(":support:logging")

    testImplementation project(":tests:api-docs")

    implementation 'org.springframework.boot:spring-boot-starter-web'
}
