spring.application.name: internal-sse-server
spring.profiles.active: local

spring:
  config:
    import:

  web.resources.add-mappings: false

server:
  port: 8083

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live
