dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'

    implementation project(":infra:client")
    implementation project(':infra:storage')
    implementation project(':core:domain')

    implementation project(":support:logging")
}

tasks.register('copyResourcesConfig', Copy) {
    from project(':core:storage').file('src/main/resources')
    from project(':support:logging').file('src/main/resources')

    into file("$projectDir/build/resources/main")

    include '*.yml'
}

processResources.dependsOn('copyResourcesConfig')
