### 홈 화면 캐릭터 정보
GET /v1/characters/home HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 홈 화면 회원 정보
GET /v1/members/home
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 홈 화면 에너지 포인트 정보
GET /v1/points/home HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

